// payin & payout 89 countries
// only payin 120 counries
// only payout & wire 3 countries
// all countries 214
export const countryList = [
  {
    label: 'Andorra 🇦🇩',
    name: 'Andorra 🇦🇩',
    payin: true,
    payout: true,
    value: 'AD',
  },
  {
    label: 'United Arab Emirates 🇦🇪',
    name: 'United Arab Emirates 🇦🇪',
    payin: true,
    payout: true,
    value: 'AE',
  },
  {
    label: 'Antigua & Barbuda 🇦🇬',
    name: 'Antigua & Barbuda 🇦🇬',
    payin: true,
    payout: false,
    value: 'AG',
  },
  {
    label: 'Anguilla 🇦🇮',
    name: 'Anguilla 🇦🇮',
    payin: true,
    payout: true,
    value: 'AI',
  },
  {
    label: 'Armenia 🇦🇲',
    name: 'Armenia 🇦🇲',
    payin: true,
    payout: false,
    value: 'AM',
  },
  {
    label: 'Angola 🇦🇴',
    name: 'Angola 🇦🇴',
    payin: true,
    payout: true,
    value: 'AO',
  },
  {
    label: 'Antarctica 🇦🇶',
    name: 'Antarctica 🇦🇶',
    payin: true,
    payout: false,
    value: 'AQ',
  },
  {
    label: 'Argentina 🇦🇷',
    name: 'Argentina 🇦🇷',
    payin: true,
    payout: true,
    value: 'AR',
  },
  {
    label: 'American Samoa 🇦🇸',
    name: 'American Samoa 🇦🇸',
    payin: true,
    payout: true,
    value: 'AS',
  },
  {
    label: 'Austria 🇦🇹',
    name: 'Austria 🇦🇹',
    payin: true,
    payout: true,
    value: 'AT',
  },
  {
    label: 'Australia 🇦🇺',
    name: 'Australia 🇦🇺',
    payin: true,
    payout: true,
    value: 'AU',
  },
  {
    label: 'Aruba 🇦🇼',
    name: 'Aruba 🇦🇼',
    payin: true,
    payout: false,
    value: 'AW',
  },
  {
    label: 'Åland Islands 🇦🇽',
    name: 'Åland Islands 🇦🇽',
    payin: true,
    payout: false,
    value: 'AX',
  },
  {
    label: 'Azerbaijan 🇦🇿',
    name: 'Azerbaijan 🇦🇿',
    payin: true,
    payout: true,
    value: 'AZ',
  },
  {
    label: 'Bangladesh 🇧🇩',
    name: 'Bangladesh 🇧🇩',
    payin: true,
    payout: false,
    value: 'BD',
  },
  {
    label: 'Belgium 🇧🇪',
    name: 'Belgium 🇧🇪',
    payin: true,
    payout: true,
    value: 'BE',
  },
  {
    label: 'Burkina Faso 🇧🇫',
    name: 'Burkina Faso 🇧🇫',
    payin: true,
    payout: true,
    value: 'BF',
  },
  {
    label: 'Bulgaria 🇧🇬',
    name: 'Bulgaria 🇧🇬',
    payin: true,
    payout: true,
    value: 'BG',
  },
  {
    label: 'Bahrain 🇧🇭',
    name: 'Bahrain 🇧🇭',
    payin: true,
    payout: false,
    value: 'BH',
  },
  {
    label: 'Burundi 🇧🇮',
    name: 'Burundi 🇧🇮',
    payin: true,
    payout: false,
    value: 'BI',
  },
  {label: 'Benin 🇧🇯', name: 'Benin 🇧🇯', payin: true, payout: true, value: 'BJ'},
  {
    label: 'St. Barthélemy 🇧🇱',
    name: 'St. Barthélemy 🇧🇱',
    payin: true,
    payout: false,
    value: 'BL',
  },
  {
    label: 'Bermuda 🇧🇲',
    name: 'Bermuda 🇧🇲',
    payin: true,
    payout: true,
    value: 'BM',
  },
  {
    label: 'Brunei 🇧🇳',
    name: 'Brunei 🇧🇳',
    payin: true,
    payout: false,
    value: 'BN',
  },
  {
    label: 'Bolivia 🇧🇴',
    name: 'Bolivia 🇧🇴',
    payin: true,
    payout: false,
    value: 'BO',
  },
  {
    label: 'Bonaire 🇧🇶',
    name: 'Bonaire 🇧🇶',
    payin: true,
    payout: false,
    value: 'BQ',
  },
  {
    label: 'Brazil 🇧🇷',
    name: 'Brazil 🇧🇷',
    payin: true,
    payout: true,
    value: 'BR',
  },
  {
    label: 'Brunei Darussalam 🇧🇳',
    name: 'Brunei Darussalam 🇧🇳',
    payin: true,
    payout: false,
    value: 'BN',
  },
  {
    label: 'Bhutan 🇧🇹',
    name: 'Bhutan 🇧🇹',
    payin: true,
    payout: false,
    value: 'BT',
  },
  {
    label: 'Bouvet Island 🇧🇻',
    name: 'Bouvet Island 🇧🇻',
    payin: true,
    payout: false,
    value: 'BV',
  },
  {
    label: 'Belarus 🇧🇾',
    name: 'Belarus 🇧🇾',
    payin: true,
    payout: false,
    value: 'BY',
  },
  {
    label: 'Belize 🇧🇿',
    name: 'Belize 🇧🇿',
    payin: true,
    payout: false,
    value: 'BZ',
  },
  {
    label: 'Canada 🇨🇦',
    name: 'Canada 🇨🇦',
    payin: true,
    payout: true,
    value: 'CA',
  },
  {
    label: 'Cocos (Keeling) Islands 🇨🇨',
    name: 'Cocos (Keeling) Islands 🇨🇨',
    payin: true,
    payout: false,
    value: 'CC',
  },
  {
    label: 'Congo - Kinshasa 🇨🇩',
    name: 'Congo - Kinshasa 🇨🇩',
    payin: true,
    payout: false,
    value: 'CD',
  },
  {
    label: 'Switzerland 🇨🇭',
    name: 'Switzerland 🇨🇭',
    payin: true,
    payout: true,
    value: 'CH',
  },
  {
    label: 'Côte d’Ivoire 🇨🇮',
    name: 'Côte d’Ivoire 🇨🇮',
    payin: true,
    payout: false,
    value: 'CI',
  },
  {
    label: 'Cook Islands 🇨🇰',
    name: 'Cook Islands 🇨🇰',
    payin: true,
    payout: false,
    value: 'CK',
  },
  {label: 'Chile 🇨🇱', name: 'Chile 🇨🇱', payin: true, payout: true, value: 'CL'},
  {
    label: 'Cameroon 🇨🇲',
    name: 'Cameroon 🇨🇲',
    payin: true,
    payout: true,
    value: 'CM',
  },
  {label: 'China 🇨🇳', name: 'China 🇨🇳', payin: true, payout: true, value: 'CN'},
  {
    label: 'Colombia 🇨🇴',
    name: 'Colombia 🇨🇴',
    payin: true,
    payout: false,
    value: 'CO',
  },
  {
    label: 'Costa Rica 🇨🇷',
    name: 'Costa Rica 🇨🇷',
    payin: true,
    payout: false,
    value: 'CR',
  },
  {
    label: 'Cape Verde 🇨🇻',
    name: 'Cape Verde 🇨🇻',
    payin: true,
    payout: false,
    value: 'CV',
  },
  {
    label: 'Curaçao 🇨🇼',
    name: 'Curaçao 🇨🇼',
    payin: true,
    payout: false,
    value: 'CW',
  },
  {
    label: 'Christmas Island 🇨🇽',
    name: 'Christmas Island 🇨🇽',
    payin: true,
    payout: false,
    value: 'CX',
  },
  {
    label: 'Cyprus 🇨🇾',
    name: 'Cyprus 🇨🇾',
    payin: true,
    payout: false,
    value: 'CY',
  },
  {
    label: 'Czechia 🇨🇿',
    name: 'Czechia 🇨🇿',
    payin: true,
    payout: false,
    value: 'CZ',
  },
  {
    label: 'Germany 🇩🇪',
    name: 'Germany 🇩🇪',
    payin: true,
    payout: true,
    value: 'DE',
  },
  {label: 'Djibouti 🇩🇯', name: 'Djibouti 🇩🇯', value: 'DJ'},
  {
    label: 'Denmark 🇩🇰',
    name: 'Denmark 🇩🇰',
    payin: true,
    payout: true,
    value: 'DK',
  },
  {
    label: 'Dominica 🇩🇲',
    name: 'Dominica 🇩🇲',
    payin: true,
    payout: false,
    value: 'DM',
  },
  {
    label: 'Dominican Republic 🇩🇴',
    name: 'Dominican Republic 🇩🇴',
    payin: true,
    payout: false,
    value: 'DO',
  },
  {
    label: 'Algeria 🇩🇿',
    name: 'Algeria 🇩🇿',
    payin: true,
    payout: false,
    value: 'DZ',
  },
  {
    label: 'Ecuador 🇪🇨',
    name: 'Ecuador 🇪🇨',
    payin: true,
    payout: false,
    value: 'EC',
  },
  {
    label: 'Estonia 🇪🇪',
    name: 'Estonia 🇪🇪',
    payin: true,
    payout: true,
    value: 'EE',
  },
  {
    label: 'Eswatini 🇸🇿',
    name: 'Eswatini 🇸🇿',
    payin: true,
    payout: false,
    value: 'SZ',
  },
  {
    label: 'Egypt 🇪🇬',
    name: 'Egypt 🇪🇬',
    payin: true,
    payout: false,
    value: 'EG',
  },
  {
    label: 'Western Sahara 🇪🇭',
    name: 'Western Sahara 🇪🇭',
    payin: true,
    payout: false,
    value: 'EH',
  },
  {
    label: 'Eritrea 🇪🇷',
    name: 'Eritrea 🇪🇷',
    payin: true,
    payout: false,
    value: 'ER',
  },
  {label: 'Spain 🇪🇸', name: 'Spain 🇪🇸', payin: true, payout: true, value: 'ES'},
  {
    label: 'Ethiopia 🇪🇹',
    name: 'Ethiopia 🇪🇹',
    payin: true,
    payout: false,
    value: 'ET',
  },
  {
    label: 'Finland 🇫🇮',
    name: 'Finland 🇫🇮',
    payin: true,
    payout: true,
    value: 'FI',
  },
  {label: 'Fiji 🇫🇯', name: 'Fiji 🇫🇯', payin: true, payout: false, value: 'FJ'},
  {
    label: 'Falkland Islands 🇫🇰',
    name: 'Falkland Islands 🇫🇰',
    payin: true,
    payout: false,
    value: 'FK',
  },
  {
    label: 'Micronesia 🇫🇲',
    name: 'Micronesia 🇫🇲',
    payin: true,
    payout: false,
    value: 'FM',
  },
  {
    label: 'Faroe Islands 🇫🇴',
    name: 'Faroe Islands 🇫🇴',
    payin: true,
    payout: false,
    value: 'FO',
  },
  {
    label: 'France 🇫🇷',
    name: 'France 🇫🇷',
    payin: true,
    payout: true,
    value: 'FR',
  },
  {
    label: 'Gabon 🇬🇦',
    name: 'Gabon 🇬🇦',
    payin: true,
    payout: false,
    value: 'GA',
  },
  {
    label: 'United Kingdom 🇬🇧',
    name: 'United Kingdom 🇬🇧',
    payin: true,
    payout: true,
    value: 'GB',
  },
  {
    label: 'Grenada 🇬🇩',
    name: 'Grenada 🇬🇩',
    payin: true,
    payout: false,
    value: 'GD',
  },
  {
    label: 'Georgia 🇬🇪',
    name: 'Georgia 🇬🇪',
    payin: true,
    payout: true,
    value: 'GE',
  },
  {
    label: 'French Guiana 🇬🇫',
    name: 'French Guiana 🇬🇫',
    payin: true,
    payout: false,
    value: 'GF',
  },
  {
    label: 'Guernsey 🇬🇬',
    name: 'Guernsey 🇬🇬',
    payin: true,
    payout: true,
    value: 'GG',
  },
  {
    label: 'Gibraltar 🇬🇮',
    name: 'Gibraltar 🇬🇮',
    payin: true,
    payout: true,
    value: 'GI',
  },
  {
    label: 'Greenland 🇬🇱',
    name: 'Greenland 🇬🇱',
    payin: true,
    payout: false,
    value: 'GL',
  },
  {
    label: 'Gambia 🇬🇲',
    name: 'Gambia 🇬🇲',
    payin: true,
    payout: false,
    value: 'GM',
  },
  {
    label: 'Guinea 🇬🇳',
    name: 'Guinea 🇬🇳',
    payin: true,
    payout: false,
    value: 'GN',
  },
  {
    label: 'Guadeloupe 🇬🇵',
    name: 'Guadeloupe 🇬🇵',
    payin: true,
    payout: false,
    value: 'GP',
  },
  {
    label: 'Equatorial Guinea 🇬🇶',
    name: 'Equatorial Guinea 🇬🇶',
    payin: true,
    payout: false,
    value: 'GQ',
  },
  {
    label: 'Greece 🇬🇷',
    name: 'Greece 🇬🇷',
    payin: true,
    payout: true,
    value: 'GR',
  },
  {
    label: 'South Georgia & South Sandwich Islands 🇬🇸',
    name: 'South Georgia & South Sandwich Islands 🇬🇸',
    payin: true,
    payout: false,
    value: 'GS',
  },
  {
    label: 'Guatemala 🇬🇹',
    name: 'Guatemala 🇬🇹',
    payin: true,
    payout: true,
    value: 'GT',
  },
  {label: 'Guam 🇬🇺', name: 'Guam 🇬🇺', payin: true, payout: true, value: 'GU'},
  {label: 'Guinea-Bissau 🇬🇼', name: 'Guinea-Bissau 🇬🇼', value: 'GW'},
  {
    label: 'Hong Kong SAR China 🇭🇰',
    name: 'Hong Kong SAR China 🇭🇰',
    payin: true,
    payout: true,
    value: 'HK',
  },
  {
    label: 'Heard & McDonald Islands 🇭🇲',
    name: 'Heard & McDonald Islands 🇭🇲',
    payin: true,
    payout: false,
    value: 'HM',
  },
  {
    label: 'Honduras 🇭🇳',
    name: 'Honduras 🇭🇳',
    payin: true,
    payout: false,
    value: 'HN',
  },
  {
    label: 'Holy See 🇻🇦',
    name: 'Holy See 🇻🇦',
    payin: true,
    payout: true,
    value: 'VA',
  },
  {
    label: 'Croatia 🇭🇷',
    name: 'Croatia 🇭🇷',
    payin: true,
    payout: true,
    value: 'HR',
  },
  {
    label: 'Haiti 🇭🇹',
    name: 'Haiti 🇭🇹',
    payin: true,
    payout: false,
    value: 'HT',
  },
  {
    label: 'Hungary 🇭🇺',
    name: 'Hungary 🇭🇺',
    payin: true,
    payout: true,
    value: 'HU',
  },
  {
    label: 'Indonesia 🇮🇩',
    name: 'Indonesia 🇮🇩',
    payin: true,
    payout: true,
    value: 'ID',
  },
  {
    label: 'Ireland 🇮🇪',
    name: 'Ireland 🇮🇪',
    payin: true,
    payout: true,
    value: 'IE',
  },
  {
    label: 'Israel 🇮🇱',
    name: 'Israel 🇮🇱',
    payin: true,
    payout: true,
    value: 'IL',
  },
  {
    label: 'Isle of Man 🇮🇲',
    name: 'Isle of Man 🇮🇲',
    payin: true,
    payout: true,
    value: 'IM',
  },
  {label: 'India 🇮🇳', name: 'India 🇮🇳', payin: true, payout: true, value: 'IN'},
  {
    label: 'British Indian Ocean Territory 🇮🇴',
    name: 'British Indian Ocean Territory 🇮🇴',
    payin: true,
    payout: false,
    value: 'IO',
  },
  {
    label: 'Iceland 🇮🇸',
    name: 'Iceland 🇮🇸',
    payin: false,
    payout: true,
    value: 'IS',
  },
  {label: 'Italy 🇮🇹', name: 'Italy 🇮🇹', payin: true, payout: true, value: 'IT'},
  {
    label: 'Jersey 🇯🇪',
    name: 'Jersey 🇯🇪',
    payin: true,
    payout: true,
    value: 'JE',
  },
  {
    label: 'Jordan 🇯🇴',
    name: 'Jordan 🇯🇴',
    payin: true,
    payout: true,
    value: 'JO',
  },
  {label: 'Japan 🇯🇵', name: 'Japan 🇯🇵', payin: true, payout: true, value: 'JP'},
  {label: 'Kenya 🇰🇪', name: 'Kenya 🇰🇪', payin: true, payout: true, value: 'KE'},
  {
    label: 'Kyrgyzstan 🇰🇬',
    name: 'Kyrgyzstan 🇰🇬',
    payin: true,
    payout: false,
    value: 'KG',
  },
  {
    label: 'Cambodia 🇰🇭',
    name: 'Cambodia 🇰🇭',
    payin: false,
    payout: true,
    value: 'KH',
  },
  {
    label: 'Kiribati 🇰🇮',
    name: 'Kiribati 🇰🇮',
    payin: true,
    payout: false,
    value: 'KI',
  },
  {
    label: 'Comoros 🇰🇲',
    name: 'Comoros 🇰🇲',
    payin: true,
    payout: false,
    value: 'KM',
  },
  {
    label: 'St. Kitts & Nevis 🇰🇳',
    name: 'St. Kitts & Nevis 🇰🇳',
    payin: true,
    payout: false,
    value: 'KN',
  },
  {
    label: 'South Korea 🇰🇷',
    name: 'South Korea 🇰🇷',
    payin: true,
    payout: true,
    value: 'KR',
  },
  {
    label: 'Kuwait 🇰🇼',
    name: 'Kuwait 🇰🇼',
    payin: true,
    payout: false,
    value: 'KW',
  },
  {
    label: 'Cayman Islands 🇰🇾',
    name: 'Cayman Islands 🇰🇾',
    payin: true,
    payout: true,
    value: 'KY',
  },
  {
    label: 'Kazakhstan 🇰🇿',
    name: 'Kazakhstan 🇰🇿',
    payin: true,
    payout: false,
    value: 'KZ',
  },
  {
    label: 'St. Lucia 🇱🇨',
    name: 'St. Lucia 🇱🇨',
    payin: true,
    payout: false,
    value: 'LC',
  },
  {
    label: 'Liechtenstein 🇱🇮',
    name: 'Liechtenstein 🇱🇮',
    payin: true,
    payout: true,
    value: 'LI',
  },
  {
    label: 'Liberia 🇱🇷',
    name: 'Liberia 🇱🇷',
    payin: true,
    payout: false,
    value: 'LR',
  },
  {
    label: 'Lesotho 🇱🇸',
    name: 'Lesotho 🇱🇸',
    payin: true,
    payout: false,
    value: 'LS',
  },
  {
    label: 'Lithuania 🇱🇹',
    name: 'Lithuania 🇱🇹',
    payin: true,
    payout: true,
    value: 'LT',
  },
  {
    label: 'Luxembourg 🇱🇺',
    name: 'Luxembourg 🇱🇺',
    payin: true,
    payout: true,
    value: 'LU',
  },
  {
    label: 'Latvia 🇱🇻',
    name: 'Latvia 🇱🇻',
    payin: true,
    payout: true,
    value: 'LV',
  },
  {
    label: 'Macao 🇲🇴',
    name: 'Macao 🇲🇴',
    payin: true,
    payout: false,
    value: 'MO',
  },
  {
    label: 'Morocco 🇲🇦',
    name: 'Morocco 🇲🇦',
    payin: true,
    payout: false,
    value: 'MA',
  },
  {
    label: 'Monaco 🇲🇨',
    name: 'Monaco 🇲🇨',
    payin: true,
    payout: true,
    value: 'MC',
  },
  {
    label: 'Moldova 🇲🇩',
    name: 'Moldova 🇲🇩',
    payin: true,
    payout: false,
    value: 'MD',
  },
  {
    label: 'Montenegro 🇲🇪',
    name: 'Montenegro 🇲🇪',
    payin: true,
    payout: false,
    value: 'ME',
  },
  {
    label: 'St. Martin 🇲🇫',
    name: 'St. Martin 🇲🇫',
    payin: true,
    payout: false,
    value: 'MF',
  },
  {
    label: 'Madagascar 🇲🇬',
    name: 'Madagascar 🇲🇬',
    payin: true,
    payout: true,
    value: 'MG',
  },
  {
    label: 'Marshall Islands 🇲🇭',
    name: 'Marshall Islands 🇲🇭',
    payin: true,
    payout: false,
    value: 'MH',
  },
  {
    label: 'Macedonia 🇲🇰',
    name: 'Macedonia 🇲🇰',
    payin: true,
    payout: false,
    value: 'MK',
  },
  {
    label: 'Macau SAR China 🇲🇴',
    name: 'Macau SAR China 🇲🇴',
    payin: true,
    payout: true,
    value: 'MO',
  },
  {
    label: 'Northern Mariana Islands 🇲🇵',
    name: 'Northern Mariana Islands 🇲🇵',
    payin: true,
    payout: false,
    value: 'MP',
  },
  {
    label: 'Martinique 🇲🇶',
    name: 'Martinique 🇲🇶',
    payin: true,
    payout: false,
    value: 'MQ',
  },
  {
    label: 'Mauritania 🇲🇷',
    name: 'Mauritania 🇲🇷',
    payin: true,
    payout: false,
    value: 'MR',
  },
  {
    label: 'Montserrat 🇲🇸',
    name: 'Montserrat 🇲🇸',
    payin: true,
    payout: false,
    value: 'MS',
  },
  {label: 'Malta 🇲🇹', name: 'Malta 🇲🇹', payin: true, payout: true, value: 'MT'},
  {
    label: 'Maldives 🇲🇻',
    name: 'Maldives 🇲🇻',
    payin: true,
    payout: false,
    value: 'MV',
  },
  {
    label: 'Malawi 🇲🇼',
    name: 'Malawi 🇲🇼',
    payin: true,
    payout: true,
    value: 'MW',
  },
  {
    label: 'Mexico 🇲🇽',
    name: 'Mexico 🇲🇽',
    payin: true,
    payout: true,
    value: 'MX',
  },
  {
    label: 'Malaysia 🇲🇾',
    name: 'Malaysia 🇲🇾',
    payin: true,
    payout: true,
    value: 'MY',
  },
  {
    label: 'Mozambique 🇲🇿',
    name: 'Mozambique 🇲🇿',
    payin: true,
    payout: true,
    value: 'MZ',
  },
  {
    label: 'Namibia 🇳🇦',
    name: 'Namibia 🇳🇦',
    payin: true,
    payout: false,
    value: 'NA',
  },
  {
    label: 'New Caledonia 🇳🇨',
    name: 'New Caledonia 🇳🇨',
    payin: true,
    payout: false,
    value: 'NC',
  },
  {label: 'Niger 🇳🇪', name: 'Niger 🇳🇪', payin: true, payout: true, value: 'NE'},
  {
    label: 'Norfolk Island 🇳🇫',
    name: 'Norfolk Island 🇳🇫',
    payin: true,
    payout: false,
    value: 'NF',
  },
  {
    label: 'Nigeria 🇳🇬',
    name: 'Nigeria 🇳🇬',
    payin: true,
    payout: false,
    value: 'NG',
  },
  {
    label: 'Netherlands 🇳🇱',
    name: 'Netherlands 🇳🇱',
    payin: true,
    payout: true,
    value: 'NL',
  },
  {
    label: 'Norway 🇳🇴',
    name: 'Norway 🇳🇴',
    payin: true,
    payout: true,
    value: 'NO',
  },
  {
    label: 'Nepal 🇳🇵',
    name: 'Nepal 🇳🇵',
    payin: true,
    payout: false,
    value: 'NP',
  },
  {
    label: 'Nauru 🇳🇷',
    name: 'Nauru 🇳🇷',
    payin: true,
    payout: false,
    value: 'NR',
  },
  {label: 'Niue 🇳🇺', name: 'Niue 🇳🇺', payin: true, payout: false, value: 'NU'},
  {
    label: 'New Zealand 🇳🇿',
    name: 'New Zealand 🇳🇿',
    payin: true,
    payout: true,
    value: 'NZ',
  },
  {label: 'Oman 🇴🇲', name: 'Oman 🇴🇲', payin: true, payout: false, value: 'OM'},
  {label: 'Peru 🇵🇪', name: 'Peru 🇵🇪', payin: true, payout: true, value: 'PE'},
  {
    label: 'French Polynesia 🇵🇫',
    name: 'French Polynesia 🇵🇫',
    payin: true,
    payout: false,
    value: 'PF',
  },
  {
    label: 'Papua New Guinea 🇵🇬',
    name: 'Papua New Guinea 🇵🇬',
    payin: true,
    payout: false,
    value: 'PG',
  },
  {
    label: 'Philippines 🇵🇭',
    name: 'Philippines 🇵🇭',
    payin: true,
    payout: true,
    value: 'PH',
  },
  {
    label: 'Poland 🇵🇱',
    name: 'Poland 🇵🇱',
    payin: true,
    payout: true,
    value: 'PL',
  },
  {
    label: 'St. Pierre & Miquelon 🇵🇲',
    name: 'St. Pierre & Miquelon 🇵🇲',
    payin: true,
    payout: false,
    value: 'PM',
  },
  {
    label: 'Pitcairn Islands 🇵🇳',
    name: 'Pitcairn Islands 🇵🇳',
    payin: true,
    payout: true,
    value: 'PN',
  },
  {
    label: 'Puerto Rico 🇵🇷',
    name: 'Puerto Rico 🇵🇷',
    payin: true,
    payout: true,
    value: 'PR',
  },
  {
    label: 'Portugal 🇵🇹',
    name: 'Portugal 🇵🇹',
    payin: true,
    payout: true,
    value: 'PT',
  },
  {
    label: 'Palau 🇵🇼',
    name: 'Palau 🇵🇼',
    payin: true,
    payout: false,
    value: 'PW',
  },
  {
    label: 'Paraguay 🇵🇾',
    name: 'Paraguay 🇵🇾',
    payin: true,
    payout: false,
    value: 'PY',
  },
  {
    label: 'Qatar 🇶🇦',
    name: 'Qatar 🇶🇦',
    payin: true,
    payout: false,
    value: 'QA',
  },
  {
    label: 'Réunion 🇷🇪',
    name: 'Réunion 🇷🇪',
    payin: true,
    payout: false,
    value: 'RE',
  },
  {
    label: 'Romania 🇷🇴',
    name: 'Romania 🇷🇴',
    payin: true,
    payout: true,
    value: 'RO',
  },
  {
    label: 'Serbia 🇷🇸',
    name: 'Serbia 🇷🇸',
    payin: true,
    payout: false,
    value: 'RS',
  },
  {
    label: 'Russia 🇷🇺',
    name: 'Russia 🇷🇺',
    payin: true,
    payout: false,
    value: 'RU',
  },
  {
    label: 'Rwanda 🇷🇼',
    name: 'Rwanda 🇷🇼',
    payin: true,
    payout: false,
    value: 'RW',
  },
  {
    label: 'Saudi Arabia 🇸🇦',
    name: 'Saudi Arabia 🇸🇦',
    payin: true,
    payout: false,
    value: 'SA',
  },
  {
    label: 'Solomon Islands 🇸🇧',
    name: 'Solomon Islands 🇸🇧',
    payin: true,
    payout: false,
    value: 'SB',
  },
  {
    label: 'Seychelles 🇸🇨',
    name: 'Seychelles 🇸🇨',
    payin: true,
    payout: false,
    value: 'SC',
  },
  {
    label: 'Sweden 🇸🇪',
    name: 'Sweden 🇸🇪',
    payin: true,
    payout: true,
    value: 'SE',
  },
  {
    label: 'Singapore 🇸🇬',
    name: 'Singapore 🇸🇬',
    payin: true,
    payout: true,
    value: 'SG',
  },
  {
    label: 'St. Helena 🇸🇭',
    name: 'St. Helena 🇸🇭',
    payin: true,
    payout: false,
    value: 'SH',
  },
  {
    label: 'Slovenia 🇸🇮',
    name: 'Slovenia 🇸🇮',
    payin: true,
    payout: true,
    value: 'SI',
  },
  {
    label: 'Svalbard & Jan Mayen 🇸🇯',
    name: 'Svalbard & Jan Mayen 🇸🇯',
    payin: true,
    payout: false,
    value: 'SJ',
  },
  {
    label: 'Slovakia 🇸🇰',
    name: 'Slovakia 🇸🇰',
    payin: true,
    payout: true,
    value: 'SK',
  },
  {
    label: 'Sierra Leone 🇸🇱',
    name: 'Sierra Leone 🇸🇱',
    payin: true,
    payout: false,
    value: 'SL',
  },
  {
    label: 'Sao Tome and Principe 🇸🇹',
    name: 'Sao Tome and Principe 🇸🇹',
    payin: true,
    payout: false,
    value: 'ST',
  },
  {
    label: 'San Marino 🇸🇲',
    name: 'San Marino 🇸🇲',
    payin: true,
    payout: true,
    value: 'SM',
  },
  {
    label: 'Senegal 🇸🇳',
    name: 'Senegal 🇸🇳',
    payin: true,
    payout: true,
    value: 'SN',
  },
  {
    label: 'Suriname 🇸🇷',
    name: 'Suriname 🇸🇷',
    payin: true,
    payout: false,
    value: 'SR',
  },
  {
    label: 'El Salvador 🇸🇻',
    name: 'El Salvador 🇸🇻',
    payin: true,
    payout: false,
    value: 'SV',
  },
  {
    label: 'Sint Maarten 🇸🇽',
    name: 'Sint Maarten 🇸🇽',
    payin: true,
    payout: false,
    value: 'SX',
  },
  {
    label: 'Tristan da Cunha 🇹🇦',
    name: 'Tristan da Cunha 🇹🇦',
    payin: true,
    payout: false,
    value: 'TA',
  },
  {
    label: 'Turks & Caicos Islands 🇹🇨',
    name: 'Turks & Caicos Islands 🇹🇨',
    payin: true,
    payout: false,
    value: 'TC',
  },
  {label: 'Chad 🇹🇩', name: 'Chad 🇹🇩', payin: true, payout: true, value: 'TD'},
  {
    label: 'French Southern Territories 🇹🇫',
    name: 'French Southern Territories 🇹🇫',
    payin: true,
    payout: false,
    value: 'TF',
  },
  {label: 'Togo 🇹🇬', name: 'Togo 🇹🇬', payin: true, payout: false, value: 'TG'},
  {
    label: 'Thailand 🇹🇭',
    name: 'Thailand 🇹🇭',
    payin: true,
    payout: true,
    value: 'TH',
  },
  {
    label: 'Tajikistan 🇹🇯',
    name: 'Tajikistan 🇹🇯',
    payin: true,
    payout: false,
    value: 'TJ',
  },
  {
    label: 'Tokelau 🇹🇰',
    name: 'Tokelau 🇹🇰',
    payin: true,
    payout: false,
    value: 'TK',
  },
  {
    label: 'Timor-Leste 🇹🇱',
    name: 'Timor-Leste 🇹🇱',
    payin: true,
    payout: false,
    value: 'TL',
  },
  {
    label: 'Turkmenistan 🇹🇲',
    name: 'Turkmenistan 🇹🇲',
    payin: true,
    payout: false,
    value: 'TM',
  },
  {
    label: 'Turkey 🇹🇷',
    name: 'Turkey 🇹🇷',
    payin: true,
    payout: true,
    value: 'TR',
  },
  {
    label: 'Tonga 🇹🇴',
    name: 'Tonga 🇹🇴',
    payin: true,
    payout: false,
    value: 'TO',
  },
  {
    label: 'Tuvalu 🇹🇻',
    name: 'Tuvalu 🇹🇻',
    payin: true,
    payout: false,
    value: 'TV',
  },
  {
    label: 'Taiwan 🇹🇼',
    name: 'Taiwan 🇹🇼',
    payin: true,
    payout: true,
    value: 'TW',
  },
  {
    label: 'Tanzania 🇹🇿',
    name: 'Tanzania 🇹🇿',
    payin: true,
    payout: true,
    value: 'TZ',
  },
  {
    label: 'U.S. Outlying Islands 🇺🇲',
    name: 'U.S. Outlying Islands 🇺🇲',
    payin: true,
    payout: true,
    value: 'UM',
  },
  {
    label: 'United States 🇺🇸',
    name: 'United States 🇺🇸',
    payin: true,
    payout: true,
    value: 'US',
  },
  {
    label: 'Uruguay 🇺🇾',
    name: 'Uruguay 🇺🇾',
    payin: true,
    payout: true,
    value: 'UY',
  },
  {
    label: 'Uzbekistan 🇺🇿',
    name: 'Uzbekistan 🇺🇿',
    payin: true,
    payout: false,
    value: 'UZ',
  },
  {
    label: 'St. Vincent & Grenadines 🇻🇨',
    name: 'St. Vincent & Grenadines 🇻🇨',
    payin: true,
    payout: false,
    value: 'VC',
  },
  {
    label: 'British Virgin Islands 🇻🇬',
    name: 'British Virgin Islands 🇻🇬',
    payin: true,
    payout: true,
    value: 'VG',
  },
  {
    label: 'U.S. Virgin Islands 🇻🇮',
    name: 'U.S. Virgin Islands 🇻🇮',
    payin: false,
    payout: true,
    value: 'VI',
  },
  {
    label: 'Vietnam 🇻🇳',
    name: 'Vietnam 🇻🇳',
    payin: true,
    payout: true,
    value: 'VN',
  },
  {
    label: 'Wallis & Futuna 🇼🇫',
    name: 'Wallis & Futuna 🇼🇫',
    payin: true,
    payout: false,
    value: 'WF',
  },
  {
    label: 'Samoa 🇼🇸',
    name: 'Samoa 🇼🇸',
    payin: true,
    payout: false,
    value: 'WS',
  },
  {
    label: 'Mayotte 🇾🇹',
    name: 'Mayotte 🇾🇹',
    payin: true,
    payout: false,
    value: 'YT',
  },
  {
    label: 'South Africa 🇿🇦',
    name: 'South Africa 🇿🇦',
    payin: true,
    payout: true,
    value: 'ZA',
  },
  {
    label: 'Zambia 🇿🇲',
    name: 'Zambia 🇿🇲',
    payin: true,
    payout: false,
    value: 'ZM',
  },
];

/**
 * Returns the ISO code of the country by provided name
 *
 * @param { string } name - the name of the country
 *
 * @returns { string } - The ISO country code
 */
export const getCountryCodeFromName = (name) => {
  const countryObj = countryList.find((x) => x.name === name);

  return countryObj?.value;
};
