export const EventTypeState = {
  creationReqToJoin: 'creationReqToJoin',
  requestToJoinCreated: 'requestToJoinCreated',
  requestToJoinExecuted: 'requestToJoinExecuted',
  requestToJoinAccepted: 'requestToJoinAccepted',
  subscriptionPaymentConfirmed: 'subscriptionPaymentConfirmed',
  subscriptionCanceledByUser: 'subscriptionCanceledByUser',
  fundingRequestAccepted: 'fundingRequestAccepted',
  fundingRequestCreated: 'fundingRequestCreated',
  fundingRequestExecuted: 'fundingRequestExecuted',
  fundingRequestRejected: 'fundingRequestRejected',
  voteCreated: 'voteCreated',
  cardCreated: 'cardCreated',
  paymentFailed: 'paymentFailed',
  messageCreated: 'messageCreated',
  commonCreated: 'commonCreated',
  commonWhitelisted: 'commonWhitelisted',
  commonMemberAdded: 'commonMemberAdded',
};

export const EventTitleState = {
  creationReqToJoin: 'Request To Join Created',
  requestToJoinCreated: 'Request To Join Created',
  requestToJoinExecuted: 'Request To Join Executed',
  requestToJoinAccepted: 'Request To Join Accepted',
  subscriptionPaymentConfirmed: 'Subscription Payment Confirmed',
  subscriptionCanceledByUser: 'Subscription Canceled By User',
  fundingRequestAccepted: 'Funding Request Accepted',
  fundingRequestCreated: 'Funding Request Created',
  fundingRequestExecuted: 'Funding Request Executed',
  fundingRequestRejected: 'Funding Request Rejected',
  cardCreated: 'Card Created',
  voteCreated: 'Vote Created',
  paymentFailed: 'Payment Failed',
  messageCreated: 'Message Created',
  commonCreated: 'Common Created',
  commonWhitelisted: 'Common Whitelisted',
  commonMemberAdded: 'Common Member Added',
};
