import {StyleSheet} from 'react-native';
import colors from './colors';
import font from './font';

const appFontFamily = {
  fontFamily: 'HelveticaNeue',
};

export default StyleSheet.create({
  h1Black: {
    ...font.primary.bold,
    ...font.fontSize(4),
    lineHeight: 29,
    textAlign: 'center',
    color: colors.black,
  },
  h2Black: {
    ...font.primary.bold,
    ...font.fontSize(3),
    textAlign: 'center',
    color: colors.black,
  },
  h3Black: {
    ...font.primary.bold,
    ...font.fontSize(2),
    textAlign: 'center',
    color: colors.black,
  },
  h4Black: {
    ...font.primary.bold,
    ...font.fontSize(1),
    textAlign: 'center',
    color: colors.black,
  },
  buttonblack: {
    ...appFontFamily,
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.black,
  },
  buttoncenterwhite: {
    ...appFontFamily,
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ffffff',
  },
  buttonblue: {
    ...appFontFamily,
    fontSize: 16,
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.mainBlue,
  },
  buttonred: {
    ...appFontFamily,
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.error,
  },
  runningboldblue: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: colors.mainBlue,
  },
  paragraphitaliclightGray: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'italic',
    letterSpacing: 0,
    textAlign: 'right',
    color: colors.paleblue,
  },
  textFieldplaceholder: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.grey3,
  },
  textFieldfocus: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: '#000000',
  },
  textFielddisabled: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.paleblue,
  },
  runningred: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ff1700',
  },
  runninglightGray: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: colors.grey2,
  },
  runninggray: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: colors.gray1,
  },
  runningblack: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: colors.black,
  },
  paragraphred: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.error,
  },
  tapBarUnselected: {
    ...appFontFamily,
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.grey3,
  },
  tapBarselected: {
    ...appFontFamily,
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.mainBlue,
  },
  smallBlackText: {
    ...font.primary.regular,
    ...font.fontSize(1),
    textAlign: 'center',
    color: colors.black,
  },
  ashleyjquimbacom: {
    ...appFontFamily,
    fontSize: 16,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.mainBlue,
  },
  ashleyjquimbacom2: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.grey3,
  },
  bvBmseYstWetqTFn5Au: {
    ...appFontFamily,
    fontSize: 10,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 12,
    letterSpacing: 0,
    color: colors.slate,
  },

  greyText: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.greyText,
  },

  smallGreyText: {
    ...appFontFamily,
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.grey3,
  },

  smallBoldGreyText: {
    ...appFontFamily,
    fontSize: 12,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.grey3,
  },

  orangeSmallBold: {
    ...appFontFamily,
    fontSize: 12,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: colors.orange,
  },

  blackText: {
    ...appFontFamily,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.black,
  },

  lightishGreenText: {
    ...appFontFamily,
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
    color: colors.lightishGreen,
  },

  againstText: {
    ...appFontFamily,
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
    color: colors.against,
  },

  againstTextBlack: {
    ...appFontFamily,
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
    color: colors.black,
  },

  // Custom text styles
  centered: {
    textAlign: 'center',
  },

  bold: {
    fontWeight: 'bold',
  },
});
