platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

# pre-install for permissions
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

$RNFirebaseAsStaticFramework = true
# -------------------------------------------------- #
def reactnative
  pod 'Permission-PhotoLibrary', :path => '../node_modules/react-native-permissions/ios/PhotoLibrary.podspec'
  pod 'Permission-Camera', :path => '../node_modules/react-native-permissions/ios/Camera.podspec'
  pod 'react-native-blur', path: '../node_modules/@react-native-community/blur'
end

# -------------------------------------------------- #
def native
  # Native Dependencies
  pod 'web3swift', git: 'https://github.com/matter-labs/web3swift', branch: 'master'
  pod 'KeychainAccess'
  pod 'IQKeyboardManagerSwift'
end

target 'common' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  reactnative
  native
  use_frameworks!
end

target 'common-stg' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  reactnative
  native
  use_frameworks!
end

target 'common-dev' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  reactnative
  native
  use_frameworks!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
