export enum FUNDING_ALLOCATION_STATUS {
  PENDING_PROPOSAL_APPROVAL = 'PENDING_PROPOSAL_APPROVAL',
  PASSED_INSUFFICIENT_BALANCE = 'PASSED_INSUFFICIENT_BALANCE',
  PENDING_INVOICE_UPLOAD = 'PENDING_INVOICE_UPLOAD',
  EXPIRED_INVOICES_NOT_UPLOADED = 'EXPIRED_INVOICES_NOT_UPLOADED',
  PENDING_INVOICE_APPROVAL = 'PENDING_INVOICE_APPROVAL',
  PENDING_SELLER_APPROVAL = 'PENDING_SELLER_APPROVAL',
  PENDING_WALLET_TRANSFER = 'PENDING_WALLET_TRANSFER',
  PENDING_BANK_WITHDRAWAL = 'PENDING_BANK_WITHDRAWAL',
  COMPLETED = 'COMPLETED',
}
