export enum PROPOSALS {
  MEMBER_ADMITTANCE = 'MEMBER_ADMITTANCE',
  // MEMBER_EXPULSION = 'MEMBER_EXPULSION',

  FUNDS_ALLOCATION = 'FUNDS_ALLOCATION',

  // ADD_UNSTRUCTURED_RULE = 'ADD_RULE',
  // UPDATE_UNSTRUCTURED_RULE = 'UPDATE_RULE',
  // DELETE_UNSTRUCTURED_RULE = 'DELETE_RULE',

  // ADD_PROPOSAL_RULE = 'ADD_PROPOSAL_RULE',
  // UPDATE_PROPOSAL_RULE = 'UPDATE_PROPOSAL_RULE',
  // DELETE_PROPOSAL_RULE = 'DELETE_PROPOSAL_RULE',

  FUNDS_REQUEST = 'FUNDS_REQUEST',
  UPDATE_FUNDS_REQUEST = 'UPDATE_FUNDS_REQUEST',

  // CREATE_CIRCLE = 'CREATE_NEW_CIRCLE',
  // UPDATE_CIRCLE = 'UPDATE_CIRCLE',
  // DELETE_CIRCLE = 'DELETE_CIRCLE',

  // ASSIGN_CIRCLE_TO_MEMBER = 'ASSIGN_CIRCLE_TO_MEMBER',
  // REMOVE_CIRCLE_FROM_MEMBER = 'REMOVE_CIRCLE_FROM_MEMBER',

  // DELETE_DISCUSSION = 'DELETE_DISCUSSION',
}

export enum PROPOSAL_STATE {
  PASSED = 'passed',
  FAILED = 'failed',
  COUNTDOWN = 'countdown',
}

export const ALLOWED_PROPOSALS_OPTIONS = [
  {
    value: PROPOSALS.MEMBER_ADMITTANCE,
    label: 'Member Admittance',
  },
  {
    value: PROPOSALS.FUNDS_ALLOCATION,
    label: 'Funds Allocation',
  },
  {
    value: PROPOSALS.FUNDS_REQUEST,
    label: 'Funds Request',
  },
  {
    value: PROPOSALS.UPDATE_FUNDS_REQUEST,
    label: 'Update Funds Request',
  },
  ,
];
