import {NavigationContainerRefWithCurrent} from '@react-navigation/core';
import {NAVIGATION_SCREENS} from '~/Util/constants/routes.enum';

export type AppNavigationContainerRefWithCurrent = NavigationContainerRefWithCurrent<RootNavigatorParamList>;

export type RootNavigatorParamList = {
  [NAVIGATION_SCREENS.ONBOARDING]: undefined;
  [NAVIGATION_SCREENS.TAB_STACK]: undefined;
  [NAVIGATION_SCREENS.CREATE_ACCOUNT]: undefined;
  [NAVIGATION_SCREENS.PROFILE]: undefined;
  [NAVIGATION_SCREENS.COMMON_PROFILE]: undefined;
  [NAVIGATION_SCREENS.COMMON_AGENDA]: undefined;
  [NAVIGATION_SCREENS.EDIT_COMMON]: undefined;
  [NAVIGATION_SCREENS.COMMON_EXPLANATION]: undefined;
  [NAVIGATION_SCREENS.PROPOSAL_SCREEN]: undefined;
  [NAVIGATION_SCREENS.RULES_STEP]: undefined;
  [NAVIGATION_SCREENS.INTRODUCTION_STEP]: undefined;
  [NAVIGATION_SCREENS.CONTRIBUTION_STEP]: undefined;
  [NAVIGATION_SCREENS.BILLING_DETAILS_STEP]: undefined;
  [NAVIGATION_SCREENS.PAYMENT_DETAILS_STEP]: undefined;
  [NAVIGATION_SCREENS.CREATE_COMMON]: undefined;
  [NAVIGATION_SCREENS.DISCUSSIONS]: undefined;
  [NAVIGATION_SCREENS.FULL_SCREEN_CREATION_LOADER]: undefined;
  [NAVIGATION_SCREENS.NEW_POST]: undefined;
  [NAVIGATION_SCREENS.EDIT_PROFILE]: undefined;
  [NAVIGATION_SCREENS.PDF_VIEWER]: undefined;
  [NAVIGATION_SCREENS.BROWSER]: undefined;
  [NAVIGATION_SCREENS.MY_WALLET]: undefined;
  HUDTest: undefined;
  [NAVIGATION_SCREENS.MY_PROPOSALS]: undefined;
  [NAVIGATION_SCREENS.MY_COMMONS]: undefined;
  [NAVIGATION_SCREENS.COMMON_MEMBERS]: undefined;
  [NAVIGATION_SCREENS.FUNDING_PROPOSAL]: undefined;
  [NAVIGATION_SCREENS.MONTHLY_CONTRIBUTIONS_LIST]: undefined;
  [NAVIGATION_SCREENS.MONTHLY_CONTRIBUTION]: undefined;
};
