name: Build Android and iOS
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  # install-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: |
  #         yarn
  #  build-android:
  #    needs: install-and-test
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@v2
  #    - name: Install dependencies
  #      run: |
  #        yarn
  #    - name: Build Android Release
  #      run: |
  #        cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
  #    - name: Upload Artifact
  #      uses: actions/upload-artifact@v1
  #      with:
  #        name: app-release.apk
  #        path: android/app/build/outputs/apk/release/


  lintAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test
        
      - name: Lint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
        
      - name: Save Code Linting Report JSON
        # npm script for ESLint
        # eslint --output-file eslint_report.json --format json src
        # See https://eslint.org/docs/user-guide/command-line-interface#options
        run: yarn run lint:report
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: eslint_report.json
